name: 'Deploy a Wordpress VM to Azure action - Quickstart Template'
description: 'This action helps create an Azure VM and deploy Wordpress on it'
branding:
  icon: 'play-circle'
  color: 'blue'
inputs:
  client-id:
    description: 'Client id to login to azure'
    required: true
  tenant-id:
    description: 'Tenant id to login to azure'
    required: true
  subscription-id:
    description: 'Subscription id to be used with your az login'
    required: true
  resource-group-name:
    description: 'Resource group to deploy your resources to'
    required: true
  admin-username:
    description: 'Admin username to login to vm'
    required: true
  admin-password:
    description: 'Admin password to login to vm'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Checkout master'
      uses: actions/checkout@v3
      
    - name: az cli login
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        enable-AzPSSession: false

    - name: 'Az deploy - LAMP on VM Bitnami'
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ inputs.subscription-id }}
          resourceGroupName: ${{ inputs.resource-group-name }}
          template: https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/demos/lamp-app/azuredeploy.json
          parameters: https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/demos/lamp-app/azuredeploy.parameters.json
                      authenticationType=password
                      mySqlPassword=${{ inputs.admin-password }}
                      storageAccountNamePrefix=lampappsa
                      dnsLabelPrefix=dnslabelvm
                      vmSize=Standard_D2as_v4
                      adminPasswordOrKey=${{inputs.admin-password}}
          failOnStdErr: false
